# includes
include(ExternalProject)

set(USE_OPENSSL_PC OFF)
set(ENABLE_SHARED ${LEONARDO_SHARED_ALL})

list(APPEND YUV_OPTIONS "-DENABLE_SHARED=${ENABLE_SHARED}")

# message(STATUS "[${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${YUV_OPTIONS}]")

ExternalProject_Add(YUV
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/yuv
        CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${YUV_OPTIONS}
    )